# Generated by Django 2.2.6 on 2019-11-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20191101_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rua',
            field=models.CharField(max_length=100, verbose_name='RUA'),
        ),
    ]
